import { Stustler } from "../../types/sanityTypes";

export const mockStustlers: Stustler[] = [
  // ============================
  // SOFTWARE DEVELOPERS (5)
  // ============================
  {
    _id: "sd1",
    _type: "stustler",
    name: "Laye Johnson",
    slug: { _type: "slug", current: "laye-johnson" },
    bio: "Frontend engineer specializing in modern web applications and smooth user experiences.",
    link: "https://portfolio.dev/laye",
    profileImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "/images/obaro.jpeg" },
    },
    category: "software_developer",
    subCategory: "frontend",
    toolsUsed: "React, Next.js, TailwindCSS",
    priceRange: "$300 - $800",
    experienceLevel: "intermediate",
  },
  {
    _id: "sd2",
    _type: "stustler",
    name: "Adaobi Chukwu",
    slug: { _type: "slug", current: "adaobi-chukwu" },
    bio: "Backend developer focused on scalable APIs and secure server-side logic.",
    link: "https://adaobi.dev",
    profileImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "/images/obaro.jpeg" },
    },
    category: "software_developer",
    subCategory: "backend",
    toolsUsed: "Node.js, Express, PostgreSQL",
    priceRange: "$400 - $1000",
    experienceLevel: "advanced",
  },
  {
    _id: "sd3",
    _type: "stustler",
    name: "Emmanuel Peters",
    slug: { _type: "slug", current: "emmanuel-peters" },
    bio: "Fullstack engineer building robust digital platforms end to end.",
    link: "https://emmypeters.io",
    profileImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "/images/obaro.jpeg" },
    },
    category: "software_developer",
    subCategory: "fullstack",
    toolsUsed: "React, Node.js, MongoDB",
    priceRange: "$500 - $1200",
    experienceLevel: "advanced",
  },
  {
    _id: "sd4",
    _type: "stustler",
    name: "Favour Adebayo",
    slug: { _type: "slug", current: "favour-adebayo" },
    bio: "Mobile developer who builds high-performance Android applications.",
    link: "https://mobiledevfavour.com",
    profileImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "/images/obaro.jpeg" },
    },
    category: "software_developer",
    subCategory: "mobile",
    toolsUsed: "Kotlin, Java, Jetpack Compose",
    priceRange: "$300 - $700",
    experienceLevel: "intermediate",
  },
  {
    _id: "sd5",
    _type: "stustler",
    name: "Chidera Nwosu",
    slug: { _type: "slug", current: "chidera-nwosu" },
    bio: "AI engineer passionate about building intelligent automated systems.",
    link: "https://ai-chidera.tech",
    profileImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "/images/obaro.jpeg" },
    },
    category: "software_developer",
    subCategory: "ai",
    toolsUsed: "Python, TensorFlow, PyTorch",
    priceRange: "$800 - $2000",
    experienceLevel: "advanced",
  },

  // ============================
  // DESIGNERS (5)
  // ============================
  {
    _id: "ds1",
    _type: "stustler",
    name: "Grace Oluwadamilola",
    slug: { _type: "slug", current: "grace-oluwadamilola" },
    bio: "Creative graphic designer delivering modern visuals and brand assets.",
    link: "https://gracedesigns.com",
    profileImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "/images/obaro.jpeg" },
    },
    category: "designer",
    subCategory: "graphics",
    toolsUsed: "Photoshop, Illustrator, CorelDraw",
    priceRange: "$100 - $300",
    experienceLevel: "intermediate",
  },
  {
    _id: "ds2",
    _type: "stustler",
    name: "Samuel Idoko",
    slug: { _type: "slug", current: "samuel-idoko" },
    bio: "UI/UX designer focused on intuitive and user-centered interfaces.",
    link: "https://uxsamuel.com",
    profileImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "/images/obaro.jpeg" },
    },
    category: "designer",
    subCategory: "uiux",
    toolsUsed: "Figma, Adobe XD",
    priceRange: "$150 - $500",
    experienceLevel: "intermediate",
  },
  {
    _id: "ds3",
    _type: "stustler",
    name: "Joy Essien",
    slug: { _type: "slug", current: "joy-essien" },
    bio: "Brand designer helping businesses build powerful, memorable identities.",
    link: "https://joybranding.com",
    profileImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "/images/obaro.jpeg" },
    },
    category: "designer",
    subCategory: "brand_design",
    toolsUsed: "Illustrator, Figma",
    priceRange: "$200 - $600",
    experienceLevel: "advanced",
  },
  {
    _id: "ds4",
    _type: "stustler",
    name: "Kelechi Obinna",
    slug: { _type: "slug", current: "kelechi-obinna" },
    bio: "Product designer crafting seamless digital experiences for modern apps.",
    link: "https://kelechiproduct.design",
    profileImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "/images/obaro.jpeg" },
    },
    category: "designer",
    subCategory: "product_design",
    toolsUsed: "Figma, Overflow, Whimsical",
    priceRange: "$250 - $700",
    experienceLevel: "advanced",
  },
  {
    _id: "ds5",
    _type: "stustler",
    name: "Chinelo Mark",
    slug: { _type: "slug", current: "chinelo-mark" },
    bio: "Illustrator specializing in digital and traditional art.",
    link: "https://chineloillustrations.art",
    profileImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "/images/obaro.jpeg" },
    },
    category: "designer",
    subCategory: "illustration",
    toolsUsed: "Procreate, Adobe Illustrator",
    priceRange: "$120 - $350",
    experienceLevel: "beginner",
  },

  // ============================
  // WRITERS (5)
  // ============================
  {
    _id: "wr1",
    _type: "stustler",
    name: "Michael Ogun",
    slug: { _type: "slug", current: "michael-ogun" },
    bio: "SEO content writer producing high-ranking blog articles.",
    link: "https://michaelwrites.com",
    profileImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "/images/obaro.jpeg" },
    },
    category: "writer",
    subCategory: "seo_writer",
    toolsUsed: "Grammarly, SurferSEO",
    priceRange: "$50 - $200",
    experienceLevel: "intermediate",
  },
  {
    _id: "wr2",
    _type: "stustler",
    name: "Rose Akpan",
    slug: { _type: "slug", current: "rose-akpan" },
    bio: "Copywriter crafting persuasive brand messaging and ad copies.",
    link: "https://rose-copy.com",
    profileImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "/images/obaro.jpeg" },
    },
    category: "writer",
    subCategory: "copywriter",
    toolsUsed: "Notion, Hemingway",
    priceRange: "$150 - $400",
    experienceLevel: "advanced",
  },
  {
    _id: "wr3",
    _type: "stustler",
    name: "Tunde Lawal",
    slug: { _type: "slug", current: "tunde-lawal" },
    bio: "Technical writer specializing in developer documentation.",
    link: "https://tundewrites.dev",
    profileImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "/images/obaro.jpeg" },
    },
    category: "writer",
    subCategory: "technical_writer",
    toolsUsed: "Markdown, GitHub, Notion",
    priceRange: "$200 - $500",
    experienceLevel: "intermediate",
  },
  {
    _id: "wr4",
    _type: "stustler",
    name: "Victoria James",
    slug: { _type: "slug", current: "victoria-james" },
    bio: "Creative writer bringing stories and scripts to life.",
    link: "https://victoriastories.art",
    profileImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "/images/obaro.jpeg" },
    },
    category: "writer",
    subCategory: "creative_writer",
    toolsUsed: "Google Docs, Final Draft",
    priceRange: "$80 - $250",
    experienceLevel: "beginner",
  },
  {
    _id: "wr5",
    _type: "stustler",
    name: "Ibrahim Sulaiman",
    slug: { _type: "slug", current: "ibrahim-sulaiman" },
    bio: "Academic writer delivering high-quality research content.",
    link: "https://ibrahimacademy.com",
    profileImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "/images/obaro.jpeg" },
    },
    category: "writer",
    subCategory: "academic_writer",
    toolsUsed: "Zotero, MS Word",
    priceRange: "$100 - $300",
    experienceLevel: "advanced",
  },

  // ============================
  // SOCIAL MEDIA MANAGERS (5)
  // ============================
  {
    _id: "sm1",
    _type: "stustler",
    name: "Blessing Ojo",
    slug: { _type: "slug", current: "blessing-ojo" },
    bio: "Helps brands grow organically through structured content systems.",
    link: "https://blessingsocial.com",
    profileImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "/images/obaro.jpeg" },
    },
    category: "social_media_manager",
    subCategory: "content_creation",
    toolsUsed: "Canva, CapCut, Buffer",
    priceRange: "$100 - $400",
    experienceLevel: "intermediate",
  },
  {
    _id: "sm2",
    _type: "stustler",
    name: "Daniel Igwe",
    slug: { _type: "slug", current: "daniel-igwe" },
    bio: "Social media strategist focused on brand engagement and growth.",
    link: "https://danielstrategy.com",
    profileImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "/images/obaro.jpeg" },
    },
    category: "social_media_manager",
    subCategory: "strategy",
    toolsUsed: "Hootsuite, Metricool",
    priceRange: "$150 - $600",
    experienceLevel: "advanced",
  },
  {
    _id: "sm3",
    _type: "stustler",
    name: "Esther Bello",
    slug: { _type: "slug", current: "esther-bello" },
    bio: "Instagram page manager helping SMEs maintain consistent branding.",
    link: "https://estherpages.com",
    profileImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "/images/obaro.jpeg" },
    },
    category: "social_media_manager",
    subCategory: "page_management",
    toolsUsed: "Canva, Later",
    priceRange: "$120 - $350",
    experienceLevel: "intermediate",
  },
  {
    _id: "sm4",
    _type: "stustler",
    name: "John Paul",
    slug: { _type: "slug", current: "john-paul" },
    bio: "Content curator and social brand image consultant.",
    link: "https://johnpaulcreative.com",
    profileImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "/images/obaro.jpeg" },
    },
    category: "social_media_manager",
    subCategory: "brand_management",
    toolsUsed: "Canva, Trello",
    priceRange: "$100 - $400",
    experienceLevel: "beginner",
  },
  {
    _id: "sm5",
    _type: "stustler",
    name: "Precious Henry",
    slug: { _type: "slug", current: "precious-henry" },
    bio: "Helps businesses run ads and track results effectively.",
    link: "https://preciousads.com",
    profileImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "/images/obaro.jpeg" },
    },
    category: "social_media_manager",
    subCategory: "ads_management",
    toolsUsed: "Facebook Ads, Google Ads",
    priceRange: "$200 - $800",
    experienceLevel: "advanced",
  },

  // ============================
  // VIRTUAL ASSISTANTS (5)
  // ============================
  {
    _id: "va1",
    _type: "stustler",
    name: "Mary Felix",
    slug: { _type: "slug", current: "mary-felix" },
    bio: "Virtual assistant helping CEOs stay organized with tasks.",
    link: "https://maryva.com",
    profileImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "/images/obaro.jpeg" },
    },
    category: "virtual_assistant",
    subCategory: "admin_support",
    toolsUsed: "Google Workspace, Notion",
    priceRange: "$80 - $250",
    experienceLevel: "intermediate",
  },
  {
    _id: "va2",
    _type: "stustler",
    name: "Stella Osei",
    slug: { _type: "slug", current: "stella-osei" },
    bio: "VA specialized in email management and client communication.",
    link: "https://stellava.com",
    profileImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "/images/obaro.jpeg" },
    },
    category: "virtual_assistant",
    subCategory: "email_management",
    toolsUsed: "Gmail, HubSpot",
    priceRange: "$70 - $200",
    experienceLevel: "beginner",
  },
  {
    _id: "va3",
    _type: "stustler",
    name: "Ronke Ayeni",
    slug: { _type: "slug", current: "ronke-ayeni" },
    bio: "Expert in scheduling, operations, and task automation.",
    link: "https://ronkeops.com",
    profileImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "/images/obaro.jpeg" },
    },
    category: "virtual_assistant",
    subCategory: "operations_support",
    toolsUsed: "Notion, ClickUp",
    priceRange: "$100 - $300",
    experienceLevel: "advanced",
  },
  {
    _id: "va4",
    _type: "stustler",
    name: "Faith Amadi",
    slug: { _type: "slug", current: "faith-amadi" },
    bio: "Social media VA for busy creators and small businesses.",
    link: "https://faithva.com",
    profileImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "/images/obaro.jpeg" },
    },
    category: "virtual_assistant",
    subCategory: "social_media_va",
    toolsUsed: "Canva, Trello",
    priceRange: "$90 - $250",
    experienceLevel: "intermediate",
  },
  {
    _id: "va5",
    _type: "stustler",
    name: "Hope Danladi",
    slug: { _type: "slug", current: "hope-danladi" },
    bio: "VA specialized in research, summaries, and documentation.",
    link: "https://hoperesearchva.com",
    profileImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "/images/obaro.jpeg" },
    },
    category: "virtual_assistant",
    subCategory: "research_va",
    toolsUsed: "Notion, Google Docs",
    priceRange: "$60 - $200",
    experienceLevel: "beginner",
  },

  // ============================
  // DATA ANALYSTS (5)
  // ============================
  {
    _id: "da1",
    _type: "stustler",
    name: "Kelvin Musa",
    slug: { _type: "slug", current: "kelvin-musa" },
    bio: "Data analyst transforming raw data into actionable insights.",
    link: "https://kelvindata.com",
    profileImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "/images/obaro.jpeg" },
    },
    category: "data_analyst",
    subCategory: "bi_analysis",
    toolsUsed: "Power BI, Excel",
    priceRange: "$150 - $500",
    experienceLevel: "intermediate",
  },
  {
    _id: "da2",
    _type: "stustler",
    name: "Rita Asuquo",
    slug: { _type: "slug", current: "rita-asuquo" },
    bio: "Analyst specializing in dashboards and KPI tracking.",
    link: "https://ritainsights.com",
    profileImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "/images/obaro.jpeg" },
    },
    category: "data_analyst",
    subCategory: "dashboarding",
    toolsUsed: "Tableau, Power BI",
    priceRange: "$200 - $600",
    experienceLevel: "advanced",
  },
  {
    _id: "da3",
    _type: "stustler",
    name: "Joshua Ebuka",
    slug: { _type: "slug", current: "joshua-ebuka" },
    bio: "Data cleaning and processing specialist for businesses.",
    link: "https://joshdataclean.com",
    profileImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "/images/obaro.jpeg" },
    },
    category: "data_analyst",
    subCategory: "data_cleaning",
    toolsUsed: "Python, Excel",
    priceRange: "$80 - $250",
    experienceLevel: "beginner",
  },
  {
    _id: "da4",
    _type: "stustler",
    name: "Gloria Martins",
    slug: { _type: "slug", current: "gloria-martins" },
    bio: "Predictive data analyst using ML models for forecasting.",
    link: "https://gloriaanalyst.com",
    profileImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "/images/obaro.jpeg" },
    },
    category: "data_analyst",
    subCategory: "predictive_analysis",
    toolsUsed: "Python, Scikit-learn",
    priceRange: "$300 - $800",
    experienceLevel: "advanced",
  },
  {
    _id: "da5",
    _type: "stustler",
    name: "Samuel Adeoye",
    slug: { _type: "slug", current: "samuel-adeoye" },
    bio: "Data visualization specialist helping brands tell stories with data.",
    link: "https://samuelviz.com",
    profileImage: {
      _type: "image",
      asset: { _type: "reference", _ref: "/images/obaro.jpeg" },
    },
    category: "data_analyst",
    subCategory: "visualization",
    toolsUsed: "Tableau, Power BI",
    priceRange: "$150 - $400",
    experienceLevel: "intermediate",
  },
];
